### ISSUE TITLE
email bouncing back

### ISSUE THREAD

**Issue by dabeaz** [affan-salman/jsonplus-mode#1]
I am only opening this issue to let you know that all email sent to you is bouncing back as undeliverable.  Hopefully this issue will find you.

**Comment by affan-salman** [comment]
Oh, I did not know this.  Thanks for letting me know and creatively getting
through to me.

**Comment by dabeaz** [comment]
https://github.com/dabeaz-course/sicp_2024_07

I'm showing you have access.  All other details are there.

**Comment by affan-salman** [comment]
Ah, I found at least the email from GitHub a little while ago — on a
different email account and I was looking for email from your account in my
scaleux.io inbox.

I found the zoom details in the repo.  Thanks!

Due to my couple chronic health conditions and time zone difference, I will
try to manage to attend live as much as I can and attempt to work though
the rest in my own time — It’ll be totally worth it for me, David.  Much
appreciated!
